"""campos user and profile

Revision ID: eb3c3856ae4b
Revises: f3af8ac6cbe2
Create Date: 2023-06-09 10:49:59.120073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3c3856ae4b'
down_revision = 'f3af8ac6cbe2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
